# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/artful64"
  config.vm.host_name = "lechuck"
#  config.vm.network "private_network", type: "dhcp"
#  config.vm.network "private_network", type: "dhcp"
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 4096
    libvirt.cpus = 2
  end
  config.vm.provider :virtualbox do |vb|
    vb.memory = 4096
    vb.cpus = 2
    # system("
    #  if [ #{ARGV[0]} = 'up' ]; then
    #    system('./myscript.sh')
    #  fi
    # ")
  end
  $pre = <<-SHELL
    #  rightsize the disk...
    parted /dev/sda --script -- resizepart 1 -1
    resize2fs /dev/sda1
    proxy=#{ENV['APT_PROXY']}
    # export http_proxy=$proxy
    # export https_proxy=$proxy
    echo $HOSTNAME
    if [ "$proxy" != "" ]; then
      echo "Acquire::http::Proxy \\\"$proxy\\\";" > /etc/apt/apt.conf
    fi

    # monkey_island bits
    apt-get update && apt-get -y upgrade && \
    apt-get install -y sudo python python-pip mongodb openssl npm git \
      gcc-multilib  python-pip python-dev libffi-dev upx libssl-dev libc++1
    ln -s /home/vagrant/monkey/monkey_island /var/monkey_island
    echo Cryptog
    python -m pip install cryptography --upgrade
    cd /home/vagrant/monkey/monkey_island
    echo Req
    python -m pip install -r requirements.txt

    # chaos_monkey bits
    cd /home/vagrant/monkey/chaos_monkey
    python -m pip install -r requirements.txt
  SHELL
  $script = <<-SHELL
    proxy=#{ENV['APT_PROXY']}
    # export http_proxy=$proxy
    # export https_proxy=$proxy

    # monkey_island
    cd /home/vagrant/monkey/monkey_island
    bash -x linux/create_certificate.sh
    cd /home/vagrant/monkey/monkey_island/cc/ui
    npm update
    npm run dist
    cd
    # if binaries are built...
    cp -r /home/vagrant/monkey/dist/* monkey/monkey_island/cc/binaries/
    echo "cd /home/vagrant/monkey/monkey_island/cc && python -u main.py" > run.sh
    chmod 755 run.sh

    # chaos bit
    cd /home/vagrant/monkey/chaos_monkey/monkey_utils/sambacry_monkey_runner
    bash -x build.sh

    cd /home/vagrant/monkey/chaos_monkey
    if [ ! -d "bin" ]; then mkdir bin; fi
    cp /home/vagrant//monkey/chaos_monkey/monkey_utils/sambacry_monkey_runner/*.so bin/ && \
    bash -x nbuild_linux.sh
    cd
    # put our own over
    cp /home/vagrant/monkey/chaos_monkey/dist/* monkey/monkey_island/cc/binaries/
    echo "Bing, toast is done!"
  SHELL
  config.vm.provision "shell", inline: $pre, privileged: true
  config.vm.provision "shell", inline: $script, privileged: false
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.synced_folder "../", "/home/vagrant/monkey"
#    type: "sshfs",
#    sshfs_opts_append: "-o idmap=user -o uid=1000 -o gid=1000 -o follow_symlinks"
end
